# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Production Build to the Google Play"
  lane :release do
    gradle(
	  task: "clean bundleRelease"
	)
    supply(
      skip_upload_images: 'false',
      skip_upload_screenshots: 'false',
	  skip_upload_metadata: 'false',
	  skip_upload_changelogs: 'false',
      track: 'production',
      package_name: 'me.impa.knockonports',
      aab_paths: ["app/build/outputs/bundle/release/app-release.aab"]
    )
  end

  desc "Submit a new Beta Build to the Google Play"
  lane :beta do
    gradle(
	  task: "clean bundleRelease"
	)
    supply(
      skip_upload_images: 'true',
      skip_upload_screenshots: 'true',
	  skip_upload_metadata: 'true',
	  skip_upload_changelogs: 'false',
      track: 'beta',
      package_name: 'me.impa.knockonports',
      aab_paths: ["app/build/outputs/bundle/release/app-release.aab"]
    )
  end

  desc "Submit a new Alpha Build to the Google Play"
  lane :alpha do
    gradle(
	  task: "clean bundleRelease"
	)
    supply(
      skip_upload_images: 'true',
      skip_upload_screenshots: 'true',
	  skip_upload_metadata: 'true',
	  skip_upload_changelogs: 'true',
      track: 'alpha',
      package_name: 'me.impa.knockonports',
      aab_paths: ["app/build/outputs/bundle/release/app-release.aab"]
    )
  end

#  desc "Deploy a new version to the Google Play"
#  lane :deploy do
#    gradle(task: "clean assembleRelease")
#    upload_to_play_store
#  end
  
  lane :screenshots do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    capture_android_screenshots
  end
end
